FROM node:20.5.1-alpine

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
RUN ls -a
RUN npm install
RUN npm run build
RUN npm -g rm
RUN rm -r ./src
RUN npm install --only=production
CMD ["node","build/worker.js"]

## this is stage two , where the app actually runs
##FROM node:20.5.1-alpine
##WORKDIR /app
##COPY package.json ./
##RUN npm install --only=production
##COPY --from=0 /app/build .
##RUN npm install pm2 -g
##CMD ["node","worker.js"]